apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Values.name }}-postgresql"
  name: "{{ .Values.name }}-postgresql"
spec:
  replicas: 1
  selector:
    name: "{{ .Values.name }}-postgresql"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: "{{ .Values.name }}-postgresql"
    spec:
      containers:
      - capabilities: {}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: "{{ .Values.name }}-data"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: pgdata
        emptyDir: {}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:{{ .Values.db.version }}
        namespace: openshift
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
